package org.telegram.ui.Components;
import android.graphics.Canvas;
import android.os.SystemClock;
import android.text.*;
import android.text.style.*;
import org.telegram.messenger.*;
import java.util.*;
public final class LumaTypingAnimatorRegressionTest {
    static int assertions,failures,cases;
    interface Test {void run()throws Exception;}
    static void check(boolean value,String label){assertions++;if(!value)throw new AssertionError(label);}
    static void test(String label,Test test){
        cases++;MessagesController.values.clear();SystemClock.now=1000;
        try{test.run();System.out.println("PASS "+label);}catch(Throwable error){failures++;System.out.println("FAIL "+label+": "+error);}
    }
    static boolean hiddenSpan(Object value){return value.getClass().getSimpleName().equals("HiddenTypingSpan")||(value instanceof ForegroundColorSpan&&((ForegroundColorSpan)value).color==0);}
    static int hidden(ModelEditable text){int count=0;for(ModelEditable.Span s:text.spans)if(hiddenSpan(s.value))count++;return count;}
    static int[] ranges(ModelEditable text){ArrayList<Integer> values=new ArrayList<>();for(ModelEditable.Span s:text.spans)if(hiddenSpan(s.value)){values.add(s.start);values.add(s.end);}return values.stream().mapToInt(i->i).toArray();}
    static LumaTypingAnimator animator(EditTextBoldCursor view){LumaTypingAnimator animator=new LumaTypingAnimator();animator.setTarget(view,true);return animator;}
    static void commit(LumaTypingAnimator animator,EditTextBoldCursor view,int start,int end,String value){animator.beginImeCommit();try{view.replace(start,end,value);}finally{animator.endImeChange();}}
    static Canvas draw(LumaTypingAnimator animator,EditTextBoldCursor view){String text=view.text==null?null:view.text.toString();int selectionStart=view.selectionStart,selectionEnd=view.selectionEnd;Canvas canvas=new Canvas();animator.beforeDraw(view);animator.afterDraw(view,canvas);check(Objects.equals(text,view.text==null?null:view.text.toString()),"draw leaves native text unchanged");check(selectionStart==view.selectionStart&&selectionEnd==view.selectionEnd,"draw leaves selection unchanged");check(canvas.saves==0,"canvas saves balanced");return canvas;}
    public static void main(String[] args){
        test("adjacent Latin/Cyrillic insertions survive",()->{EditTextBoldCursor v=new EditTextBoldCursor("");LumaTypingAnimator a=animator(v);v.replace(0,0,"a");v.replace(1,1,"б");check(hidden(v.text)==2,"both adjacent letters animated");SystemClock.now+=100;check(draw(a,v).draws.size()>0,"draw produces glyphs");});
        test("middle insertion/selection replacement",()->{EditTextBoldCursor v=new EditTextBoldCursor("abcd");LumaTypingAnimator a=animator(v);v.replace(1,3,"XY");check(v.text.toString().equals("aXYd"),"replacement text");check(Arrays.equals(ranges(v.text),new int[]{1,2,2,3}),"only selected replacement hidden");v.replace(1,1,"!");check(v.selectionStart==2,"caret belongs to native edit");draw(a,v);});
        test("delete an animated character",()->{EditTextBoldCursor v=new EditTextBoldCursor("");LumaTypingAnimator a=animator(v);v.replace(0,0,"ab");v.replace(0,1,"");check(v.text.toString().equals("b"),"deleted content absent");check(hidden(v.text)==1,"remaining letter tracked at shifted offset");SystemClock.now+=500;draw(a,v);check(hidden(v.text)==0,"delete does not strand a span");});
        test("IME commit word and no-animation option",()->{EditTextBoldCursor v=new EditTextBoldCursor("");LumaTypingAnimator a=animator(v);commit(a,v,0,0,"  привет ");check(Arrays.equals(ranges(v.text),new int[]{2,8}),"word batch excludes surrounding spaces");a.clear(v);LumaTextAnimation.setSwipeMode(LumaTextAnimation.SWIPE_NO_ANIMATION);commit(a,v,0,v.text.length(),"hello");check(hidden(v.text)==5,"selection replacement still per-letter");a.clear(v);commit(a,v,v.text.length(),v.text.length()," bye");check(hidden(v.text)==0,"pure swipe commit honors no-animation");});
        test("pure IME commit uses explicit swipe-by-letter mode",()->{LumaTextAnimation.setSwipeMode(LumaTextAnimation.SWIPE_BY_LETTER);EditTextBoldCursor v=new EditTextBoldCursor("");LumaTypingAnimator a=animator(v);commit(a,v,0,0,"hello");check(Arrays.equals(ranges(v.text),new int[]{0,1,1,2,2,3,3,4,4,5}),"pure committed word has five separate glyph ranges");check(v.text.toString().equals("hello")&&v.selectionStart==5&&v.selectionEnd==5,"IME content and caret preserved");SystemClock.now+=100;Canvas canvas=draw(a,v);check(canvas.draws.size()==10,"blur and sharp emitted independently for five letters");for(int i=0;i<5;i++){check(canvas.draws.get(2*i).text.equals("hello".substring(i,i+1)),"each blur run is exactly one committed letter");check(canvas.draws.get(2*i+1).text.equals("hello".substring(i,i+1)),"each sharp run is exactly one committed letter");}SystemClock.now+=220;draw(a,v);check(hidden(v.text)==0,"by-letter commit expires normally");});
        test("live tuning and mode changes affect only subsequent glyphs",()->{LumaTextAnimation.setSpeedLevel(LumaTextAnimation.SPEED_SMOOTH);LumaTextAnimation.setHeightLevel(LumaTextAnimation.HEIGHT_HIGH);LumaTextAnimation.setBlurLevel(LumaTextAnimation.BLUR_STRONG);LumaTextAnimation.setSwipeMode(LumaTextAnimation.SWIPE_WHOLE_WORD);EditTextBoldCursor v=new EditTextBoldCursor("");LumaTypingAnimator a=animator(v);commit(a,v,0,0,"word");check(hidden(v.text)==1,"initial commit is one word batch");SystemClock.now+=100;Canvas before=draw(a,v);check(before.draws.size()==2,"original word has blur and sharp runs");LumaTextAnimation.setSpeedLevel(LumaTextAnimation.SPEED_FAST);LumaTextAnimation.setHeightLevel(LumaTextAnimation.HEIGHT_LOW);LumaTextAnimation.setBlurLevel(LumaTextAnimation.BLUR_LIGHT);LumaTextAnimation.setSwipeMode(LumaTextAnimation.SWIPE_BY_LETTER);Canvas changed=draw(a,v);check(changed.draws.size()==before.draws.size(),"changing mode does not split a live word batch");for(int i=0;i<before.draws.size();i++){Canvas.Draw old=before.draws.get(i),next=changed.draws.get(i);check(old.text.equals(next.text)&&old.x==next.x&&old.y==next.y&&old.alpha==next.alpha,"current duration/lift/alpha preserved at the same clock instant");}commit(a,v,4,4,"new");check(Arrays.equals(ranges(v.text),new int[]{0,4,4,5,5,6,6,7}),"next pure commit uses new by-letter mode alongside previous live batch");SystemClock.now+=221;draw(a,v);check(Arrays.equals(ranges(v.text),new int[]{0,4}),"new fast letters expire while old smooth word retains its captured duration");SystemClock.now=1460;draw(a,v);check(hidden(v.text)==0,"old word expires at its original 460 ms deadline");commit(a,v,7,7,"next");check(hidden(v.text)==4,"new by-letter commit starts before disable");LumaTextAnimation.setEnabled(false);draw(a,v);check(hidden(v.text)==0,"disabling live animation restores native text");LumaTextAnimation.setEnabled(true);Canvas enabled=draw(a,v);check(hidden(v.text)==0&&enabled.draws.isEmpty(),"reenabling does not resurrect cancelled glyphs");commit(a,v,11,11,"z");check(hidden(v.text)==1&&v.text.toString().equals("wordnewnextz"),"reenabled animator handles only subsequent input");a.clear(v);});
        test("composition restart and autocorrection",()->{EditTextBoldCursor v=new EditTextBoldCursor("");LumaTypingAnimator a=animator(v);a.beginImeComposing();v.replace(0,0,"ca");a.endImeChange();SystemClock.now+=80;a.beginImeComposing();v.replace(0,2,"cat");a.endImeChange();check(hidden(v.text)==1,"whole replacement does not replay unchanged prefix");SystemClock.now+=80;commit(a,v,0,3,"cat");check(hidden(v.text)==0,"same final commit native and unchanged");commit(a,v,0,3,"car");check(Arrays.equals(ranges(v.text),new int[]{2,3}),"only corrected suffix animates");});
        test("paste and multiline retain native text",()->{EditTextBoldCursor v=new EditTextBoldCursor("");LumaTypingAnimator a=animator(v);v.replace(0,0,"x".repeat(100000));check(hidden(v.text)==0,"huge paste not animated");v.replace(0,v.text.length(),"one\ntwo");check(hidden(v.text)==0,"line break paste native");check(v.text.toString().equals("one\ntwo"),"line break content preserved");draw(a,v);});
        test("rapid edits bounded then expire",()->{EditTextBoldCursor v=new EditTextBoldCursor("");LumaTypingAnimator a=animator(v);for(int i=0;i<1000;i++){v.replace(v.text.length(),v.text.length(),"a");check(hidden(v.text)<=72,"active spans bounded");}SystemClock.now+=1000;draw(a,v);check(hidden(v.text)==0,"all animations expire");check(v.text.length()==1000,"all typed characters remain");});
        test("replacement span inside committed word stays native",()->{EditTextBoldCursor v=new EditTextBoldCursor("icon");LumaTypingAnimator a=animator(v);v.text.setSpan(new ReplacementSpan(),0,4,33);a.beforeTextChanged("",0,0,4);a.onTextChanged(v.text,0,0,4);a.beginImeCommit();a.afterTextChanged(v.text);a.endImeChange();check(hidden(v.text)==0,"word batch must not conceal replacement content");});
        test("styled paste and late style stay native",()->{EditTextBoldCursor v=new EditTextBoldCursor("bold");LumaTypingAnimator a=animator(v);v.text.setSpan(new StyleSpan(),0,4,33);a.beforeTextChanged("",0,0,4);a.onTextChanged(v.text,0,0,4);a.afterTextChanged(v.text);check(hidden(v.text)==0,"style not flattened by raw drawText");v.replace(4,4,"A");check(hidden(v.text)==1,"plain suffix still animated");v.text.setSpan(new ForegroundColorSpan(0xFF001122),4,5,33);draw(a,v);check(hidden(v.text)==0,"late color span reveals native glyph before draw");});
        test("combining and contextual scripts native",()->{for(String value:new String[]{"e\u0301","\u0628\u064A","\u0915\u093F","\uD83D\uDE03","1\uFE0F\u20E3"}){EditTextBoldCursor v=new EditTextBoldCursor("");LumaTypingAnimator a=animator(v);v.replace(0,0,value);check(hidden(v.text)==0,"cluster/contextual script not split: "+value);draw(a,v);}EditTextBoldCursor v=new EditTextBoldCursor("");LumaTypingAnimator a=animator(v);v.replace(0,0,"e");v.replace(1,1,"\u0301");draw(a,v);check(hidden(v.text)==0,"adding a combining mark retires its base animation");});
        test("surrogate replacement remains native",()->{EditTextBoldCursor v=new EditTextBoldCursor("\uD83D\uDE00");LumaTypingAnimator a=animator(v);v.replace(0,2,"\uD83D\uDE03");check(hidden(v.text)==0,"changed half-surrogate not hidden");v.replace(0,2,"\uD83D");check(hidden(v.text)==0,"isolated surrogate native");draw(a,v);});
        test("copies cannot carry animation markup",()->{EditTextBoldCursor v=new EditTextBoldCursor("");LumaTypingAnimator a=animator(v);v.replace(0,0,"draft");ModelEditable copy=v.text.copyForDraft();check(hidden(copy)==0,"transparent animation spans are NoCopySpan");check(copy.toString().equals("draft"),"copy content unchanged");a.clear(v);check(hidden(v.text)==0,"source also cleared");});
        test("animation cannot leak into Parcelable clipboard styles",()->{EditTextBoldCursor v=new EditTextBoldCursor("");LumaTypingAnimator a=animator(v);v.replace(0,0,"copy");for(ModelEditable.Span span:v.text.spans){if(hiddenSpan(span.value)){check(!(span.value instanceof ParcelableSpan),"transparency is not a serializable ForegroundColorSpan");check(span.value instanceof UpdateAppearance,"span keeps normal appearance invalidation contract");}}a.clear(v);});
        test("view reassignment clears previous editable",()->{EditTextBoldCursor first=new EditTextBoldCursor("");LumaTypingAnimator a=animator(first);first.replace(0,0,"a");EditTextBoldCursor second=new EditTextBoldCursor("");a.setTarget(second,true);check(hidden(first.text)==0,"previous view's text revealed");check(first.watchers.isEmpty()&&second.watchers.size()==1,"single watcher belongs to new view");a.setTarget(second,true);check(second.watchers.size()==1,"repeated target not duplicated");});
        test("Editable replacement clears retired text",()->{EditTextBoldCursor v=new EditTextBoldCursor("");LumaTypingAnimator a=animator(v);v.replace(0,0,"draft");ModelEditable old=v.text;v.replaceEditable("next");check(hidden(old)==0,"retired Editable must not keep transparent spans");draw(a,v);a.clear(v);check(hidden(v.text)==0,"new Editable also clearable");});
        test("clear survives nullable text",()->{EditTextBoldCursor v=new EditTextBoldCursor("");LumaTypingAnimator a=animator(v);v.replace(0,0,"x");ModelEditable old=v.text;v.text=null;a.clear(v);check(hidden(old)==0,"null new text still releases old owner");});
        test("disable/detach/recycle/hidden cleanup",()->{for(int mode=0;mode<4;mode++){MessagesController.values.clear();EditTextBoldCursor v=new EditTextBoldCursor("");LumaTypingAnimator a=animator(v);v.replace(0,0,"x");if(mode==0)LumaTextAnimation.setEnabled(false);if(mode==1)v.attached=false;if(mode==2)v.shown=false;if(mode==3)a.setTarget(v,false);draw(a,v);check(hidden(v.text)==0,"native visible after state change "+mode);}});
        test("transformed/password text never raw redraw",()->{for(Object transform:new Object[]{new Object(),new android.text.method.PasswordTransformationMethod()}){EditTextBoldCursor v=new EditTextBoldCursor("");v.transformation=transform;LumaTypingAnimator a=animator(v);v.replace(0,0,"Secret");check(hidden(v.text)==0,"all transformed text remains native");draw(a,v);}});
        test("scroll-space coordinates and clipped later lines",()->{EditTextBoldCursor v=new EditTextBoldCursor("a\na\na\na\na\na\na\na\na\na\n");v.scrollX=12;v.scrollY=200;v.compoundPaddingLeft=9;LumaTypingAnimator a=animator(v);v.replace(v.text.length(),v.text.length(),"b");SystemClock.now+=100;Canvas canvas=draw(a,v);check(canvas.left==12&&canvas.top==200&&canvas.right==212&&canvas.bottom==240,"clip tracks scroll coordinates");check(canvas.draws.size()>0,"line after scrollY remains animated");check(canvas.draws.get(0).x==9,"horizontal scroll not subtracted twice; compound padding used");check(canvas.draws.get(0).y>=200&&canvas.draws.get(0).y<=240,"baseline inside scrolled viewport");});
        test("word batch wrap has stable independent runs",()->{EditTextBoldCursor v=new EditTextBoldCursor("");v.layout.columns=4;LumaTypingAnimator a=animator(v);commit(a,v,0,0,"abcdefgh");SystemClock.now+=100;Canvas canvas=draw(a,v);check(canvas.draws.size()==4,"blur and sharp each cover two lines");check(canvas.draws.get(0).text.equals("abcd")&&canvas.draws.get(1).text.equals("efgh"),"wrapped word slices consistent");});
        test("RTL paragraphs and absent layout reveal native text",()->{EditTextBoldCursor v=new EditTextBoldCursor("");v.layout.paragraphDirection=-1;LumaTypingAnimator a=animator(v);v.replace(0,0,"a");draw(a,v);check(hidden(v.text)==0,"RTL paragraph not drawn with LTR x");v.layout=null;v.replace(1,1,"b");draw(a,v);check(hidden(v.text)==0,"missing layout not stranded transparent");});
        test("paint state restored and completion unhidden",()->{EditTextBoldCursor v=new EditTextBoldCursor("");v.paint.setAlpha(137);LumaTypingAnimator a=animator(v);v.replace(0,0,"x");SystemClock.now+=100;draw(a,v);check(v.paint.getAlpha()==137&&v.paint.getMaskFilter()==null,"view paint untouched");SystemClock.now+=400;Canvas canvas=draw(a,v);check(hidden(v.text)==0&&canvas.draws.isEmpty(),"finished text returns to native renderer");});
        test("synthetic watcher event safely cancels",()->{EditTextBoldCursor v=new EditTextBoldCursor("");LumaTypingAnimator a=animator(v);v.replace(0,0,"a");a.beforeTextChanged(v.text,0,0,1);a.onTextChanged(v.text,1,1,1);a.afterTextChanged(v.text);check(hidden(v.text)==0,"unreliable callback cannot leave hidden text");});
        test("settings clamp/persist/reset",()->{check(LumaTextAnimation.isEnabled(),"default enabled");for(int value=-5;value<=8;value++){int clamped=Math.max(0,Math.min(2,value));LumaTextAnimation.setSpeedLevel(value);LumaTextAnimation.setBlurLevel(value);LumaTextAnimation.setHeightLevel(value);LumaTextAnimation.setSwipeMode(value);check(LumaTextAnimation.getSpeedLevel()==clamped,"speed clamp");check(LumaTextAnimation.getBlurLevel()==clamped,"blur clamp");check(LumaTextAnimation.getHeightLevel()==clamped,"height clamp");check(LumaTextAnimation.getSwipeMode()==clamped,"swipe clamp");check(LumaTextAnimation.getCharacterDurationMs()>0&&LumaTextAnimation.getWordDurationMs()>0,"durations positive");}LumaTextAnimation.setEnabled(false);LumaTextAnimation.resetTuningSettings();check(!LumaTextAnimation.isEnabled(),"reset tuning preserves enabled choice");check(LumaTextAnimation.getSpeedLevel()==1&&LumaTextAnimation.getBlurLevel()==1&&LumaTextAnimation.getHeightLevel()==1&&LumaTextAnimation.getSwipeMode()==0,"default tuning restored");});
        test("deterministic rapid edit/IME/layout stress",()->{Random random=new Random(74);String[] edits={"a","б","\uD83D\uDE03","e\u0301","\n"," ","word","\u0628",""};EditTextBoldCursor v=new EditTextBoldCursor("");LumaTypingAnimator a=animator(v);for(int i=0;i<2000;i++){int start=random.nextInt(v.text.length()+1),end=start+random.nextInt(v.text.length()-start+1);String value=edits[random.nextInt(edits.length)];String expected=v.text.toString().substring(0,start)+value+v.text.toString().substring(end);int input=random.nextInt(3);if(input==1)a.beginImeCommit();if(input==2)a.beginImeComposing();try{v.replace(start,end,value);}finally{if(input!=0)a.endImeChange();}SystemClock.now+=random.nextInt(40);v.layout.columns=1+random.nextInt(15);v.scrollX=random.nextInt(20);v.scrollY=random.nextInt(80);draw(a,v);check(v.text.toString().equals(expected),"native edit contents exact across random sequences");check(hidden(v.text)<=72,"stress spans bounded");if(i%37==0){ModelEditable old=v.text;v.replaceEditable(v.text.toString());check(hidden(old)==0,"stress retired Editable cleaned");}}SystemClock.now+=1000;draw(a,v);check(hidden(v.text)==0,"stress ends with native visible text");});
        System.out.println("RESULT "+cases+" cases, "+assertions+" assertions, "+failures+" failures. Production animator/settings compiled verbatim; platform models, NOT Android renderer/device proof.");
        if(failures!=0)System.exit(1);
    }
}
