package org.telegram.messenger;
import android.content.Context;
import android.content.pm.PackageManager;
import org.json.JSONObject;
import org.telegram.ui.web.HttpGetTask;
import org.telegram.ui.web.HttpGetFileTask;
import java.io.File;
import java.lang.reflect.Field;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;

/** Full production controller. HTTP/UI/JSON fixture contracts, not live GitHub or Android UI. */
public final class LumaUpdaterCheck76Test {
    static int assertions,cases,failures;
    static File sandbox;
    static final String API="https://api.github.com/repos/sergeevdeonisii-dotcom/LumaGram-Android/contents/updates/latest.json";
    interface Test {void run()throws Exception;}
    static void check(boolean ok,String label){assertions++;if(!ok)throw new AssertionError(label);}
    static void test(String label,Test test)throws Exception{cases++;try{reset(label);test.run();System.out.println("PASS "+label);}catch(Throwable error){failures++;System.out.println("FAIL "+label+": "+error);}}
    static void reset(String label)throws Exception{
        Utilities.globalQueue.drain();AndroidUtilities.reset();HttpGetTask.requests.clear();HttpGetFileTask.requests.clear();JSONObject.responses.clear();
        ApplicationLoader.applicationContext.getSharedPreferences("luma_updates",Context.MODE_PRIVATE).edit().clear().apply();
        ApplicationLoader.applicationContext.root=new File(sandbox,label.replaceAll("[^A-Za-z0-9_-]","_"));
        check(ApplicationLoader.applicationContext.getFilesDir().mkdirs()||ApplicationLoader.applicationContext.getFilesDir().isDirectory(),"case sandbox exists");
        PackageManager.installedVersion=71439;
        Field instance=LumaUpdaterController.class.getDeclaredField("instance");instance.setAccessible(true);instance.set(null,null);
    }
    static LumaUpdaterController controller(){LumaUpdaterController controller=LumaUpdaterController.getInstance();Utilities.globalQueue.drain();return controller;}
    static HttpGetTask latest(){return HttpGetTask.requests.get(HttpGetTask.requests.size()-1);}
    static String manifest(String id,int version,String file){
        String body="{\"version\":\"fixture-"+version+"\",\"version_code\":"+version+",\"file_url\":\""+file+"\",\"sha256\":\""+"a".repeat(64)+"\",\"changelog\":\"Привет\"}";
        Map<String,Object> values=new HashMap<>();values.put("version","fixture-"+version);values.put("version_code",version);values.put("file_url",file);values.put("sha256","a".repeat(64));values.put("changelog","Привет");JSONObject.responses.put(body,values);return body;
    }
    static void bounds(HttpGetTask task){check(task.parallel,"update check cannot be stranded in AsyncTask serial queue");check(task.connectTimeout==5000&&task.readTimeout==10000,"finite updater transport timeouts");check(task.maxBytes==65536,"manifest body bounded to 64 KiB");check(task.strict,"HTTP error bodies cannot be interpreted as manifests");}
    static Object field(Object target,String name)throws Exception{Field field=target.getClass().getDeclaredField(name);field.setAccessible(true);return field.get(target);}
    public static void main(String[] args)throws Exception{
        sandbox=new File(args[0]);
        test("official source API first uses bounded raw media request",()->{LumaUpdaterController c=controller();AtomicInteger done=new AtomicInteger();c.checkForUpdate(true,done::incrementAndGet);HttpGetTask request=latest();check(request.url.startsWith(API+"?"),"default source starts with GitHub contents API");check(request.url.contains("ref=main"),"API targets main branch");check("application/vnd.github.raw+json".equals(request.headers.get("Accept")),"API asks for raw JSON not a base64 wrapper");bounds(request);request.deliver(manifest("api",71500,"https://github.com/fixture/luna.apk"));check(done.get()==1&&!c.isChecking()&&c.getLastError()==null&&c.getUpdate()!=null,"valid API manifest finishes once with available release");check(HttpGetTask.requests.size()==1,"valid API does not need raw fallback");});
        test("valid older API manifest is latest without error",()->{LumaUpdaterController c=controller();AtomicInteger done=new AtomicInteger();c.checkForUpdate(true,done::incrementAndGet);latest().deliver(manifest("old",PackageManager.installedVersion,"https://github.com/fixture/luna.apk"));check(done.get()==1&&!c.isChecking()&&c.getUpdate()==null&&c.getLastError()==null,"only a valid no-new-release result means latest");check(HttpGetTask.requests.size()==1,"valid older manifest does not fall back");});
        test("empty API response falls back exactly once",()->{LumaUpdaterController c=controller();AtomicInteger done=new AtomicInteger();c.checkForUpdate(true,done::incrementAndGet);HttpGetTask api=latest();api.deliver(null);check(HttpGetTask.requests.size()==2&&c.isChecking()&&done.get()==0,"empty primary retains check and callbacks while raw fallback runs");HttpGetTask raw=latest();check(raw.url.startsWith(BuildVars.LUMA_UPDATE_MANIFEST_URL+"?"),"fallback returns to exact official raw source");bounds(raw);raw.deliver(manifest("raw",71500,"https://github.com/fixture/luna.apk"));check(done.get()==1&&!c.isChecking()&&c.getLastError()==null&&c.getUpdate()!=null,"valid raw fallback accepted exactly once");check(HttpGetTask.requests.size()==2,"no extra fallback after terminal result");});
        test("superseded primary and duplicate fallback cannot finish twice",()->{LumaUpdaterController c=controller();AtomicInteger done=new AtomicInteger();c.checkForUpdate(true,done::incrementAndGet);HttpGetTask api=latest();api.deliver(null);HttpGetTask raw=latest();api.deliver(manifest("late-api",71900,"https://github.com/fixture/late-api.apk"));check(c.isChecking()&&c.getUpdate()==null&&done.get()==0&&latest()==raw,"primary callback cannot supersede its active fallback even within same generation");raw.deliver(manifest("raw",71500,"https://github.com/fixture/raw.apk"));check(!c.isChecking()&&c.getUpdate()!=null&&done.get()==1&&(int)field(c,"versionCode")==71500,"fallback alone owns terminal release");raw.deliver(manifest("duplicate-raw",71800,"https://github.com/fixture/duplicate.apk"));check(done.get()==1&&(int)field(c,"versionCode")==71500&&c.getLastError()==null,"duplicate terminal reply cannot update state or callbacks");});
        test("malformed API response falls back and reports manifest error",()->{LumaUpdaterController c=controller();AtomicInteger done=new AtomicInteger();c.checkForUpdate(true,done::incrementAndGet);latest().deliver("{not-json");check(c.isChecking()&&done.get()==0&&HttpGetTask.requests.size()==2,"invalid primary keeps callback pending for raw fallback");latest().deliver("{still-not-json");check(!c.isChecking()&&done.get()==1&&c.getUpdate()==null,"invalid fallback is terminal, not an available update");check(LocaleController.getString(R.string.LumaUpdateManifestInvalid).equals(c.getLastError()),"malformed responses report explicit manifest error, not latest");check(HttpGetTask.requests.size()==2,"invalid raw does not create infinite retry");});
        test("GitHub base64 wrapper is not an accepted update manifest",()->{LumaUpdaterController c=controller();String wrapper="{\"encoding\":\"base64\",\"content\":\"ZXhhbXBsZQ==\"}";Map<String,Object> values=new HashMap<>();values.put("encoding","base64");values.put("content","ZXhhbXBsZQ==");JSONObject.responses.put(wrapper,values);AtomicInteger done=new AtomicInteger();c.checkForUpdate(true,done::incrementAndGet);latest().deliver(wrapper);check(HttpGetTask.requests.size()==2&&c.isChecking(),"unexpected API wrapper takes the single raw fallback path");latest().deliver("broken");check(!c.isChecking()&&done.get()==1&&c.getUpdate()==null&&c.getLastError()!=null,"wrapper plus bad fallback cannot become latest or installable");});
        test("custom hidden HTTPS source is preserved with no official fallback",()->{String custom="https://private.example/own/feed/latest.json";ApplicationLoader.applicationContext.getSharedPreferences("luma_updates",Context.MODE_PRIVATE).edit().putString("manifest_url",custom).apply();LumaUpdaterController c=controller();check(custom.equals(c.getManifestUrl()),"valid saved source remains in use despite hidden source editor");AtomicInteger done=new AtomicInteger();c.checkForUpdate(true,done::incrementAndGet);HttpGetTask request=latest();check(request.url.startsWith(custom+"?"),"custom source queried directly");bounds(request);request.deliver(null);check(HttpGetTask.requests.size()==1&&!c.isChecking()&&done.get()==1&&c.getLastError()!=null,"custom failure must not silently switch to official channel");check(custom.equals(c.getManifestUrl()),"failed check does not erase custom source");c.checkForUpdate(true,done::incrementAndGet);latest().deliver("malformed");check(HttpGetTask.requests.size()==2&&!c.isChecking()&&done.get()==2,"malformed custom manifest also has no default fallback");});
        test("relative APK path uses original raw manifest base",()->{LumaUpdaterController c=controller();c.checkForUpdate(true,null);latest().deliver(manifest("relative",71500,"../releases/luna.apk"));check("https://raw.githubusercontent.com/sergeevdeonisii-dotcom/LumaGram-Android/main/releases/luna.apk".equals(field(c,"fileUrl")),"API is only transport; relative APK resolves against original raw URL");check(c.getUpdate()!=null&&c.getLastError()==null,"relative HTTPS archive accepted as pending update");});
        test("force check joins existing bounded request",()->{LumaUpdaterController c=controller();AtomicInteger first=new AtomicInteger(),joined=new AtomicInteger();c.checkForUpdate(true,first::incrementAndGet);HttpGetTask request=latest();c.checkForUpdate(true,joined::incrementAndGet);check(HttpGetTask.requests.size()==1&&c.isChecking(),"force while checking joins instead of starting duplicate network work");request.deliver(manifest("join",71500,"https://github.com/fixture/luna.apk"));check(first.get()==1&&joined.get()==1&&!c.isChecking(),"joined listeners completed exactly once");AndroidUtilities.advanceBy(31000);check(first.get()==1&&joined.get()==1&&c.getLastError()==null,"completed check watchdog cannot later convert success to failure");});
        test("watchdog terminates hung check and all joined callbacks",()->{LumaUpdaterController c=controller();AtomicInteger first=new AtomicInteger(),joined=new AtomicInteger();c.checkForUpdate(true,first::incrementAndGet);HttpGetTask request=latest();c.checkForUpdate(true,joined::incrementAndGet);AndroidUtilities.advanceBy(29999);check(c.isChecking()&&first.get()==0&&joined.get()==0,"check remains bounded but pending before deadline");AndroidUtilities.advanceBy(1);check(!c.isChecking()&&first.get()==1&&joined.get()==1&&c.getLastError()!=null,"deadline releases spinner and all callbacks once");check(request.cancelled,"watchdog also cancels actual transport");request.deliver(manifest("late",71500,"https://github.com/fixture/luna.apk"));check(c.getUpdate()==null&&first.get()==1&&joined.get()==1,"late timed-out success ignored");AndroidUtilities.advanceBy(60000);check(first.get()==1&&joined.get()==1,"timeout finish is idempotent");});
        test("fallback shares original end to end deadline",()->{LumaUpdaterController c=controller();AtomicInteger done=new AtomicInteger();c.checkForUpdate(true,done::incrementAndGet);HttpGetTask api=latest();AndroidUtilities.advanceBy(29000);api.deliver(null);HttpGetTask raw=latest();check(raw!=api&&c.isChecking()&&done.get()==0,"late fallback may start before original deadline");AndroidUtilities.advanceBy(1000);check(!c.isChecking()&&raw.cancelled&&done.get()==1&&c.getLastError()!=null,"fallback cannot reset check into another thirty second spinner");raw.deliver(manifest("late-raw",71500,"https://github.com/fixture/late.apk"));check(done.get()==1&&c.getUpdate()==null,"late raw after end-to-end deadline ignored");});
        test("UI queued result after deadline cannot revive timed out check",()->{LumaUpdaterController c=controller();AtomicInteger done=new AtomicInteger();c.checkForUpdate(true,done::incrementAndGet);HttpGetTask api=latest();AndroidUtilities.deferImmediate=true;android.os.SystemClock.now+=30001;api.deliver(manifest("queued-late",71500,"https://github.com/fixture/late.apk"));AndroidUtilities.deferImmediate=false;AndroidUtilities.drainReady();check(!c.isChecking()&&done.get()==1&&c.getUpdate()==null&&c.getLastError()!=null&&api.cancelled,"earlier deadline invalidates subsequently queued result before it reaches UI state");});
        test("source change cancels old task and guards queued old result",()->{LumaUpdaterController c=controller();AtomicInteger oldDone=new AtomicInteger();c.checkForUpdate(true,oldDone::incrementAndGet);HttpGetTask old=latest();AndroidUtilities.deferImmediate=true;old.deliver(manifest("stale",71600,"https://github.com/fixture/stale.apk"));String custom="https://replacement.example/feed/latest.json";check(c.setManifestUrl(custom),"source change accepted");HttpGetTask current=latest();check(old.cancelled&&oldDone.get()==1&&current!=old&&current.url.startsWith(custom+"?"),"source change cancels transport and releases old listeners before replacement");AndroidUtilities.deferImmediate=false;AndroidUtilities.drainReady();check(c.isChecking()&&c.getUpdate()==null&&c.getManifestUrl().equals(custom),"queued old result cannot update release or terminate new check");current.deliver(manifest("new",71500,"https://github.com/fixture/new.apk"));check(!c.isChecking()&&c.getUpdate()!=null&&c.getLastError()==null,"replacement source alone owns terminal result");AndroidUtilities.advanceBy(31000);check(c.getLastError()==null&&oldDone.get()==1,"retired watchdog cannot damage replacement success");});
        test("source change during fallback invalidates both transport stages",()->{LumaUpdaterController c=controller();AtomicInteger done=new AtomicInteger();c.checkForUpdate(true,done::incrementAndGet);HttpGetTask api=latest();api.deliver(null);HttpGetTask raw=latest();c.setManifestUrl("https://next.example/latest.json");HttpGetTask current=latest();check(raw.cancelled&&done.get()==1,"active fallback cancelled and its listeners completed");api.deliver(manifest("api-late",71800,"https://github.com/fixture/api.apk"));raw.deliver(manifest("raw-late",71900,"https://github.com/fixture/raw.apk"));check(c.isChecking()&&c.getUpdate()==null&&latest()==current,"both stale generations leave new request untouched");current.deliver(manifest("current",71500,"https://github.com/fixture/current.apk"));check(!c.isChecking()&&c.getLastError()==null,"new source can finish after both stale replies");});
        test("completion reentry owns fresh listeners and watchdog",()->{LumaUpdaterController c=controller();AtomicInteger outer=new AtomicInteger(),inner=new AtomicInteger();c.checkForUpdate(true,()->{outer.incrementAndGet();c.checkForUpdate(true,inner::incrementAndGet);});HttpGetTask first=latest();first.deliver(manifest("first",71500,"https://github.com/fixture/first.apk"));HttpGetTask second=latest();check(second!=first&&c.isChecking()&&outer.get()==1&&inner.get()==0,"reentrant completion creates separately owned request");second.deliver(manifest("second",71510,"https://github.com/fixture/second.apk"));check(!c.isChecking()&&outer.get()==1&&inner.get()==1&&c.getLastError()==null,"reentrant check finishes once without previous drain stealing callback");AndroidUtilities.advanceBy(31000);check(c.getLastError()==null&&inner.get()==1,"both completed watchdogs removed");});
        test("download cancellation reentry cannot persist stale check state",()->{LumaUpdaterController c=controller();c.checkForUpdate(true,null);latest().deliver(manifest("initial",71500,"https://github.com/fixture/initial.apk"));AtomicInteger reentered=new AtomicInteger(),oldDone=new AtomicInteger(),newDone=new AtomicInteger();String source="https://reentrant.example/latest.json";c.downloadUpdate(new LumaUpdaterController.DownloadListener(){public void onProgress(float value){}public void onFinished(File file,String error){android.content.SharedPreferences prefs=ApplicationLoader.applicationContext.getSharedPreferences("luma_updates",Context.MODE_PRIVATE);check(prefs.getInt("version_code",0)==71510&&prefs.getLong("last_check",0)>0,"valid new manifest is persisted before external cancellation listener");reentered.incrementAndGet();check(c.setManifestUrl(source),"cancellation listener can replace the source");}});check(c.isDownloading(),"old release download active before replacement manifest");c.checkForUpdate(true,oldDone::incrementAndGet);latest().deliver(manifest("changed",71510,"https://github.com/fixture/changed.apk"));HttpGetTask replacement=latest();check(reentered.get()==1&&oldDone.get()==1&&c.isChecking()&&c.getUpdate()==null&&replacement.url.startsWith(source+"?"),"download listener owns fresh source and its request after valid terminal reentry");android.content.SharedPreferences prefs=ApplicationLoader.applicationContext.getSharedPreferences("luma_updates",Context.MODE_PRIVATE);check(prefs.getLong("last_check",0)==0&&(long)field(c,"lastCheck")==0&&prefs.getInt("version_code",0)==0&&source.equals(prefs.getString("manifest_url",null)),"old terminal cannot resave last_check/release after reentrant source reset");c.checkForUpdate(true,newDone::incrementAndGet);check(latest()==replacement,"joined replacement request stays independently owned");replacement.deliver(manifest("replacement",71520,"https://github.com/fixture/replacement.apk"));check(!c.isChecking()&&newDone.get()==1&&oldDone.get()==1&&c.getLastError()==null&&(int)field(c,"versionCode")==71520,"reentrant replacement source finishes normally without stale callback drain");});
        test("one failed check callback cannot strand another",()->{LumaUpdaterController c=controller();AtomicInteger survives=new AtomicInteger();c.checkForUpdate(true,()->{throw new IllegalStateException("callback fixture");});c.checkForUpdate(true,survives::incrementAndGet);latest().deliver(manifest("good",71500,"https://github.com/fixture/good.apk"));check(!c.isChecking()&&survives.get()==1&&c.getLastError()==null,"callback exception isolated after terminal state");});
        test("clock rollback cannot suppress automatic updates", () -> {
            ApplicationLoader.applicationContext.getSharedPreferences("luma_updates", Context.MODE_PRIVATE)
                    .edit().putLong("last_check", System.currentTimeMillis() + 86400000L).apply();
            LumaUpdaterController c = controller();
            AtomicInteger done = new AtomicInteger();
            c.checkForUpdate(false, done::incrementAndGet);
            check(HttpGetTask.requests.size() == 1 && c.isChecking() && done.get() == 0,
                    "future persisted timestamp must allow a fresh automatic check");
            latest().deliver(manifest("clock-rollback", PackageManager.installedVersion, "https://github.com/fixture/luna.apk"));
            check(!c.isChecking() && done.get() == 1 && c.getLastError() == null,
                    "fresh check completes normally after clock rollback");
            check((long) field(c, "lastCheck") <= System.currentTimeMillis(),
                    "successful check replaces the future timestamp");
        });
        test("recent automatic check remains throttled", () -> {
            ApplicationLoader.applicationContext.getSharedPreferences("luma_updates", Context.MODE_PRIVATE)
                    .edit().putLong("last_check", System.currentTimeMillis() - 60000L).apply();
            LumaUpdaterController c = controller();
            AtomicInteger done = new AtomicInteger();
            c.checkForUpdate(false, done::incrementAndGet);
            check(HttpGetTask.requests.isEmpty() && !c.isChecking() && done.get() == 1,
                    "recent automatic check completes without duplicate network work");
            c.checkForUpdate(true, done::incrementAndGet);
            check(HttpGetTask.requests.size() == 1 && c.isChecking(),
                    "manual check still bypasses the normal interval");
        });
        System.out.println("RESULT updater76-controller "+cases+" cases, "+assertions+" assertions, "+failures+" failures. Full production controller; controlled HTTP/UI/JSON models, not Android/GitHub live proof.");
        if(failures>0)System.exit(1);
    }
}
